import type { Metadata } from "next";
import localFont from "next/font/local";
import "/src/styles/globals.scss";

const headFont = localFont({
  src: "./fonts/Gumi Romance.ttf",
  variable: "--font-head",
  weight: "100 900",
});

const mainFont = localFont({
  src: "./fonts/SpaceGrotesk-VariableFont_wght.ttf",
  variable: "--font-main",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${headFont.className} ${mainFont.className}`}>
        {children}
      </body>
    </html>
  );
}
