spring:
  application:
    name: dannae
  port: 8080
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
jwt:
  secret-key: '${JWT_SECRET_KEY}'

openai:
  api:
    key: '${OPENAI_API_KEY}'
  model: '${OPENAI_API_MODEL}'
